image: node:lts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - test

setup:
  stage: build
  script: make setup
  needs: []

test:version:
  stage: test
  script: npm run test:version
  needs: []

test:lint:
  stage: test
  script: npm run test:lint
  needs: ['setup']

test:unit:
  stage: test
  script: npm run test:unit
  needs: ['setup']

