image: node:lts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - test

build:
  stage: build
  script: make setup

test:
  stage: test
  script: npm run test