image: node:lts

stages:
  - setup
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install
    - npm run setup

test:version:
  stage: test
  needs: []
  cache: {}
  script: npm run test:version

test:lint:
  stage: test
  needs: ["setup"]
  script: npm run test:lint

test:unit:
  stage: test
  needs: ["setup"]
  script: npm run test:unit

build:
  stage: build
  needs: ["setup"]
  artifacts:
    paths:
      - GoodCompany.zip
  script:
    - npm run build
    - make zip
