image: node:lts

stages:
  - setup
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install

test:version:
  stage: test
  needs: []
  cache: {}
  script: npm run test:version

test:lint:
  stage: test
  needs: ["setup"]
  script: npm run test:lint

test:unit:
  stage: test
  needs: ["setup"]
  script: npm run test:unit

test:web-ext-lint:
  stage: test
  needs: ["setup"]
  script: npm run test:web-ext-lint

build:
  stage: build
  needs: ["setup"]
  artifacts:
    paths:
      - GoodCompany*.zip
  script:
    - npm run setup
    - npm run build
