image: node:lts

stages:
  - setup
  - test
  - build
  - testbuild

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install

test:version:
  stage: test
  needs: []
  cache: {}
  script: npm run test:version

test:eslint:
  stage: test
  needs: ["setup"]
  script: npm run test:lint

test:unit:
  stage: test
  needs: ["setup"]
  script: npm run test:unit

build:
  stage: build
  needs: ["setup"]
  artifacts:
    paths:
      - GoodCompany*.zip
      - addon/
  script:
    - npm run setup
    - npm run build

test:web-ext-lint:
  stage: testbuild
  needs: ["setup", "build"]
  script: npm run test:web-ext-lint

sign:
  stage: deploy
  when: manual
  needs: everything
  script: npx web-ext sign -s addon/ --api-key $MOZILLA_KEY --api-secret $MOZILLA_SECRET
